

- name: Add the user
  ansible.builtin.user:
    name: roboshop

- name: remove old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Unarchive a file that needs to be downloaded and extract also
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
